@rootUrl=http://localhost:5278/
@queueName=queue.1
@topicName=weu-dev-nadin-prices-upload-sbt
@subscription=carsales-sbts
@messageId=d2712a9d932d4ce7ba3bfbccc45c5436

### List all message-ids in a queue

GET {{rootUrl}}/queue/{{queueName}}/ids

### Peek all messages in queue

GET {{rootUrl}}/queue/{{queueName}}

### Peek one message from queue

GET {{rootUrl}}/queue/{{queueName}}/{{messageId}}
    
### List all message-ids in a topic

GET {{rootUrl}}/topic/{{topicName}}/{{subscription}}/ids

### Peek all messages in topic

GET {{rootUrl}}/topic/{{topicName}}/{{subscription}}/

### Peek one message from topic

GET {{rootUrl}}/topic/{{topicName}}/{{subscription}}/{{messageId}}

### Post message to queue

POST {{rootUrl}}/queue/{{queueName}}
Content-Type: application/xml
Subject: Example xml

<document>
    <text>Some text</text>
</document>

### Post message to topic

POST {{rootUrl}}/topic/{{topicName}}
Content-Type: application/json
Subject: Some random json

{
  "document": {
    "text": "Some text"
  }
}

### Complete message from queue

DELETE {{rootUrl}}/queue/{{queueName}}/{{messageId}}